# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: vzsjablonec/debian-ftp

pipelines:
  branches:          
    production:
      - step:
          script:
            - echo "Updating production server"
            - ssh $SSH_USER@SSH_SERVER
            - echo "Production server updated"
    testing:
      - step:
          script:
            - echo "Updating testing server"
            - ssh $SSH_USER_TEST@$SSH_SERVER_TEST
            - echo "Testing server updated"
