# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: samueldebruyn/debian-git

pipelines:
  branches:          
    production:
      - step:
          script:
            - echo "Updating production server"
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --force --user $FTP_USER --passwd $FTP_PASSWD ftpes://$FTP_SERVER
            - apt-get -qq install lftp
            - mkdir ~/.lftp
            - touch ~/.lftp/rc
            - echo -n "set ssl:verify-certificate no" > ~/.lftp/rc
            - lftp -e 'rm -r /tmp/cache; mkdir -p /tmp/cache; bye' -u $FTP_USER,$FTP_PASSWD $FTP_SERVER
            - echo "Production server updated"
    testing:
      - step:
          script:
            - echo "Updating testing server"
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --force --user $FTP_USER_TEST --passwd $FTP_PASSWD_TEST ftpes://$FTP_SERVER_TEST
            - apt-get -qq install lftp
            - mkdir ~/.lftp
            - touch ~/.lftp/rc
            - echo -n "set ssl:verify-certificate no" > ~/.lftp/rc
            - lftp -e 'rm -r /tmp/cache; mkdir -p /tmp/cache; bye' -u $FTP_USER_TEST,$FTP_PASSWD_TEST $FTP_SERVER_TEST
            - echo "Testing server updated"
  custom:
      init_production:
        - step:
            script:
              - apt-get update
              - apt-get -qq install git-ftp
              - git ftp init --user $FTP_USER --passwd $FTP_PASSWD ftpes://$FTP_SERVER
              - apt-get -qq install lftp
              - mkdir ~/.lftp
              - touch ~/.lftp/rc
              - echo -n "set ssl:verify-certificate no" > ~/.lftp/rc
              - lftp -e 'rm -r /tmp/cache; mkdir -p /tmp/cache; bye' -u $FTP_USER,$FTP_PASSWD $FTP_SERVER

      init_testing:
        - step:
            script:
              - apt-get update
              - apt-get -qq install git-ftp
              - git ftp init --user $FTP_USER_TEST --passwd $FTP_PASSWD_TEST ftpes://$FTP_SERVER_TEST
              - apt-get -qq install lftp
              - mkdir ~/.lftp
              - touch ~/.lftp/rc
              - echo -n "set ssl:verify-certificate no" > ~/.lftp/rc
              - lftp -e 'rm -r /tmp/cache; mkdir -p /tmp/cache; bye' -u $FTP_USER_TEST,$FTP_PASSWD_TEST $FTP_SERVER_TEST